Anykernel3: Setup Beryllium
Change-Id: I243a550fad8608a02b2524283cfbd85bb2335a45

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -40,7 +40,6 @@ find_slot() {
     [ "$slot" ] || slot=$($BB grep -o 'androidboot.slot=.*$' /proc/cmdline | $BB cut -d\  -f1 | $BB cut -d= -f2);
     [ "$slot" ] && slot=_$slot;
   fi;
-  [ "$slot" == "normal" ] && unset slot;
   [ "$slot" ] && echo "$slot";
 }
 setup_mountpoint() {
@@ -69,7 +68,7 @@ mount_apex() {
         $BB unzip -qo $apex apex_payload.img -d /apex;
         $BB mv -f /apex/original_apex $dest.apex 2>/dev/null;
         $BB mv -f /apex/apex_payload.img $dest.img;
-        $BB mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null && echo "$dest (direct)" >&2;
+        $BB mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
         if [ $? != 0 ]; then
           while [ $num -lt 64 ]; do
             loop=/dev/block/loop$num;
@@ -78,24 +77,22 @@ mount_apex() {
             num=$((num + 1));
             $BB losetup $loop | $BB grep -q $dest.img && break;
           done;
-          $BB mount -t ext4 -o ro,loop,noatime $loop $dest && echo "$dest (loop)" >&2;
+          $BB mount -t ext4 -o ro,loop,noatime $loop $dest;
           if [ $? != 0 ]; then
             $BB losetup -d $loop 2>/dev/null;
           fi;
         fi;
       ;;
-      *) $BB mount -o bind $apex $dest && echo "$dest (bind)" >&2;;
+      *) $BB mount -o bind $apex $dest;;
     esac;
   done;
   for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB awk '{ print $2 }'); do
     eval OLD_${var}=\$$var;
   done;
   $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB sed 's; /;=/;'); unset export;
-  $BB touch /apex/apexak3;
 }
 umount_apex() {
-  [ -f /apex/apexak3 ] || return 1;
-  echo "Unmounting apex..." >&2;
+  [ -d /apex ] || return 1;
   local dest loop var;
   for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc 2>/dev/null | $BB awk '{ print $2 }'); do
     if [ "$(eval echo \$OLD_$var)" ]; then
@@ -111,23 +108,22 @@ umount_apex() {
     [ "$loop" ] && $BB losetup -d $loop;
   done;
   [ -f /apex/apextmp ] && $BB umount /apex;
-  $BB rm -rf /apex/apexak3 /apex 2>/dev/null;
+  $BB rm -rf /apex 2>/dev/null;
 }
 mount_all() {
   local byname mount slot system;
-  echo "Mounting..." >&2;
   if ! is_mounted /cache; then
-    $BB mount /cache 2>/dev/null && echo "/cache" >&2 && UMOUNT_CACHE=1;
+    $BB mount /cache 2>/dev/null && UMOUNT_CACHE=1;
   fi;
   if ! is_mounted /data; then
-    $BB mount /data && echo "/data" >&2 && UMOUNT_DATA=1;
+    $BB mount /data && UMOUNT_DATA=1;
   fi;
-  for mount in /vendor /product /system_ext /persist; do
-    $BB mount -o ro -t auto $mount 2>/dev/null && echo "$mount (fstab)" >&2;
-  done;
+  (for mount in /vendor /product /system_ext /persist; do
+    $BB mount -o ro -t auto $mount;
+  done) 2>/dev/null;
   setup_mountpoint $ANDROID_ROOT;
   if ! is_mounted $ANDROID_ROOT; then
-    $BB mount -o ro -t auto $ANDROID_ROOT 2>/dev/null && echo "$ANDROID_ROOT (\$ANDROID_ROOT)" >&2;
+    $BB mount -o ro -t auto $ANDROID_ROOT 2>/dev/null;
   fi;
   byname=bootdevice/by-name;
   [ -d /dev/block/$byname ] || byname=$($BB find /dev/block/platform -type d -name by-name 2>/dev/null | $BB head -n1 | $BB cut -d/ -f4-);
@@ -138,15 +134,15 @@ mount_all() {
     /system)
       if ! is_mounted /system && ! is_mounted /system_root; then
         setup_mountpoint /system_root;
-        $BB mount -o ro -t auto /system_root && echo "/system_root (fstab)" >&2;
+        $BB mount -o ro -t auto /system_root;
       elif [ -f /system/system/build.prop ]; then
         setup_mountpoint /system_root;
-        $BB mount --move /system /system_root && echo "/system_root (moved)" >&2;
+        $BB mount --move /system /system_root;
       fi;
       if [ $? != 0 ]; then
         ($BB umount /system;
         $BB umount -l /system) 2>/dev/null;
-        $BB mount -o ro -t auto /dev/block/$byname/system$slot /system_root && echo "/system_root (direct)" >&2;
+        $BB mount -o ro -t auto /dev/block/$byname/system$slot /system_root;
       fi;
     ;;
   esac;
@@ -154,22 +150,20 @@ mount_all() {
   for mount in /vendor /product /system_ext; do
     if ! is_mounted $mount && [ -L /system$mount -o -L /system_root$system$mount ]; then
       setup_mountpoint $mount;
-      $BB mount -o ro -t auto /dev/block/$byname$mount$slot $mount && echo "$mount (direct)" >&2;
+      $BB mount -o ro -t auto /dev/block/$byname$mount$slot $mount;
     fi;
   done;
   if is_mounted /system_root; then
     mount_apex;
-    $BB mount -o bind /system_root$system /system && echo "/system (bind)" >&2;
+    $BB mount -o bind /system_root$system /system;
   fi;
   if ! is_mounted /persist && [ -e /dev/block/bootdevice/by-name/persist ]; then
     setup_mountpoint /persist;
-    $BB mount -o ro -t auto /dev/block/bootdevice/by-name/persist /persist && echo "/persist (direct)" >&2;
+    $BB mount -o ro -t auto /dev/block/bootdevice/by-name/persist /persist;
   fi;
-  echo " " >&2;
 }
 umount_all() {
   local mount;
-  echo "Unmounting..." >&2;
   (if [ ! -d /postinstall/tmp ]; then
     $BB umount /system;
     $BB umount -l /system;
@@ -211,7 +205,7 @@ setup_env() {
   if [ ! "$(getprop 2>/dev/null)" ]; then
     getprop() {
       local propdir propfile propval;
-      for propdir in / /system_root /system /vendor /product /product/etc /system_ext/etc /odm/etc; do
+      for propdir in / /system_root /system /vendor /product /system_ext /odm; do
         for propfile in default.prop build.prop; do
           if [ "$propval" ]; then
             break 2;
@@ -240,7 +234,6 @@ restore_env() {
   [ "$OLD_LD_PRE" ] && export LD_PRELOAD=$OLD_LD_PRE;
   [ "$OLD_LD_CFG" ] && export LD_CONFIG_FILE=$OLD_LD_CFG;
   unset OLD_LD_PATH OLD_LD_PRE OLD_LD_CFG;
-  $BB sleep 1;
   umount_all;
   [ -L /etc_link ] && $BB rm -rf /etc/*;
   (for dir in /etc /apex /system_root /system /vendor /product /system_ext /persist; do
@@ -284,14 +277,14 @@ do_devicecheck() {
   for testname in $($BB grep '^device.name.*=' anykernel.sh | $BB cut -d= -f2-); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
+        ui_print "- OK ! ";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort "! Unsupported device , This Device is $devicename . Aborting... !";
   fi;
 }
 int2ver() {
@@ -306,7 +299,7 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "Checking Android version...";
+  ui_print "- Checking Android Version...";
   supported_ver=$(file_getprop anykernel.sh supported.versions | $BB tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -441,7 +434,7 @@ do_modules() {
   cd $AKHOME;
 }
 
-show_progress 1.34 25;
+show_progress 1.34 4;
 ui_print " ";
 cleanup;
 mkdir -p $AKHOME/bin;
@@ -471,17 +464,31 @@ fi;
 
 if [ -f banner ]; then
   ui_printfile banner;
-  ui_print " " " ";
+  ui_print " ";
 fi;
 
 KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
-ui_print "$KERNEL_STRING";
+KERNEL_FOR="$(file_getprop anykernel.sh kernel.for)";
+KERNEL_COMPILER="$(file_getprop anykernel.sh kernel.compiler)";
+KERNEL_MADE="$(file_getprop anykernel.sh kernel.made)";
+KERNEL_VERSION="$(file_getprop anykernel.sh kernel.version)";
+BUILD_DATE=$(date +%Y-%m-%d)
+MESSAGE_WORD="$(file_getprop anykernel.sh message.word)";
+DEVICE_NAME="$(file_getprop anykernel.sh device.name3)";
+ui_print "_________________________________________________" " ";
+ui_print "-- Kernel Name    : $KERNEL_STRING";
+ui_print "-- Kernel Version : $KERNEL_VERSION";
+ui_print "-- Compiler       : $KERNEL_COMPILER";
+ui_print "-- Device         : beryllium";
+ui_print "-- Build Date     : $BUILD_DATE";
+ui_print "-- Maintainer     : $KERNEL_MADE";
+ui_print "_________________________________________________" " ";
 if [ -f version ]; then
   ui_print " ";
   ui_printfile version;
   ui_print " ";
 fi;
-ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " ";
+ui_print "- Preparing Environment Setup ...";
 $BB grep -oE 'AK_BASE.*' META-INF/com/google/android/updater-script >&2;
 ui_print " ";
 
@@ -491,10 +498,10 @@ do_devicecheck;
 do_versioncheck;
 do_levelcheck;
 
-ui_print "Installing...";
+ui_print "Flashing Perf+ Kernel...";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
-PATH="$AKHOME/bin:$PATH" ZIPFILE="$3" home=$AKHOME $BB ash anykernel.sh $2;
+PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
 if [ $? != 0 ]; then
   abort;
 fi;
@@ -502,11 +509,12 @@ fi;
 do_modules;
 
 debugging;
-ui_print " ";
 restore_env;
 
 if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " "Done!";
+ui_print "- Done";
+ui_print " " "_________________________________________________";
+ui_print " " "$MESSAGE_WORD" "_________________________________________________" " ";
